title: GROWTHLOG

author:
  name: Changu Kim
  email: goldrocket@knou.ac.kr

description: >- # this means to ignore newlines until "baseurl:"
  To learn is to survive.

baseurl: "" # the subpath of your site, e.g. /blog

url: "https://coldnine.github.io" # the base hostname & protocol for your site, e.g. http://example.com

github_username: coldnine

# Build settings
#theme: minima
remote_theme: jekyll/minima

# https://planetjekyll.github.io/plugins
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag

safe: true

whitelist:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag

# Minima: https://github.com/jekyll/minima
minima:
  skin: classic
  social_links:
    - { platform: github,  user_url: "https://github.com/ColdNine/coldnine.github.io" }
    - { platform: gitlab,  user_url: "https://cold9.gitlab.io/blog" }

# Talkyard
#  - https://jekyll-demo.talkyard.io/2018/01/09/installation-instructions.html
#  - https://www.talkyard.net/-/create-site/embedded-comments
#  - https://comments-for-coldnine-github-io.talkyard.net
talkyard_server_url: https://site-1jur3p7p01.talkyard.net
talkyard_script_url: https://c1.ty-cdn.net/-/talkyard-comments.min.js

timezone: Asia/Seoul